delete http://localhost:3003/api/blogs/662c8611ccc6896700df2259
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkxPTCB6ZWQiLCJpZCI6IjY2MmIzOWMyNjk5MWU4ZjU2ZWNhMzA4YSIsImlhdCI6MTcxNDE5Mzk2NiwiZXhwIjoxNzE0MTk3NTY2fQ.SxMgYzju3u4pV2Io6I1jv9OFlypsGe7iixaovljAs1Y